[theme]
primaryColor= "#8da26b" # Elementos interativos.
backgroundColor= "#FFFFFF"  # Fundo branco.
secondaryBackgroundColor="#efedec"  # Fundo da sidebar.
textColor="#40403e"  # Texto cinza.

[ui]
layout = "wide"  # Expande para ocupar a largura total.

[server]
headless = true
enableCORS = false
enableXsrfProtection = false